### ISSUE TITLE
Register does not work

### ISSUE THREAD

**Issue by andywenk** [hoodiehq/hoodie-app-something-tracker#2]
Hey there,

first of all thanks for this nice little example app. When clicking on "Register" button on top, I get this JS dialog:

<img width="985" alt="screen shot 2016-01-12 at 13 17 32" src="https://cloud.githubusercontent.com/assets/51517/12263409/1ae821b6-b92f-11e5-814e-de4b04d5e442.png">

I expected to receive a registration form or sth ...

Not sure if it is related, but I did not setup the mail functionality and am running CouchDB in Admin Party (I know it's not recommended, but on local environments you will often have that. So maybe the README could be updated. You can start the app with `npm start -- --dbUrl=http://localhost:5984` in Admin Party).

Creating and deleting tracking entries works like a charm ;-).

All the best 

Andy

**Comment by gr2m** [comment]
Hey Andy, the idea is you unter the username & password in the text fields, then click on either Login or Register, depending on what you want to do.

I agree it’s not very clear, we gotta improve that :)

**Comment by gr2m** [comment]
Does it work when you enter a username & password?

**Comment by andywenk** [comment]
oh ... I see - well that is really unclear. I think most people expect a new page or layer or sth. A form with double functionality will most likely be misunderstood ;-)

Yes it does work when I enter a username and a password. So maybe you flag this ticket with "improvement" ;-)

**Comment by gr2m** [comment]
I’ll make a follow up issue later, thanks Andy :)

**Comment by gr2m** [comment]
closing in favor of #4
